// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  bug: string;
  colorWrap: string;
  dark: string;
  dragon: string;
  electric: string;
  fairy: string;
  fighting: string;
  fire: string;
  flying: string;
  ghost: string;
  grass: string;
  ground: string;
  ice: string;
  infoWrap: string;
  label: string;
  labelWrap: string;
  normal: string;
  notFound: string;
  pictureWrap: string;
  poison: string;
  psychic: string;
  rock: string;
  root: string;
  statItem: string;
  statValue: string;
  statWrap: string;
  steel: string;
  titleName: string;
  water: string;
}
export const cssExports: CssExports;
export default cssExports;
