// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  colorYellow: string;
  fullWidth: string;
  root: string;
  small: string;
}
export const cssExports: CssExports;
export default cssExports;
